群文件状态添加
GraiaProject/Application pull request #128
Opened 2021-06-13 18:37 UTC by kamaellee

具体查阅 update说明
群文件上传暂在mah 1.11.0 api文档中未能发现，若有另外发现再次push

2021-06-13 18:42 UTC, kamaellee commented
多复制了一次 查看列表……

2021-06-19 12:07 UTC, GreyElaina commented on src/graia/application/group.py
> +    isFile: Optional[bool] = None # 是否为文件
rename to `is_file`

2021-06-19 12:07 UTC, GreyElaina commented on src/graia/application/group.py
> +    downloadTimes: Optional[int] # 下载次数
rename to `download_times`, use pydantic's Field(alias=...)

2021-06-19 12:08 UTC, GreyElaina commented on src/graia/application/group.py
> +    downloadUrl: Optional[str] = None # 文件下载链接
use snake_case plz.

2021-06-19 12:12 UTC, GreyElaina commented on src/graia/application/group.py
> +    downloadUrl: Optional[str] = None # 文件下载链接
```py
class X:
     “a summary of this field”
    field_1: str
```

所有的注释全部改成这样的形式, 以兼容 pdoc 的文档生成

2021-06-19 12:14 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileList(self, group: Union[Group, int], dir: str = '') -> List[FileList]:
rename to `getGroupFileList`;

`dir`:
```py
dir: Optional[str] = None
...
dir = dir or ""
```

2021-06-19 12:15 UTC, GreyElaina commented on src/graia/application/__init__.py
> +            group (Union[Group, int]): 群组/群组ID
遵循这个[排版规范](https://learnku.com/docs/writing-docs/typography/3957)

2021-06-19 12:16 UTC, GreyElaina commented on src/graia/application/__init__.py
> +            group (Union[Group, int]): 群组/群组ID
我要求全部的 docstring 在非特殊情况下都应遵循此规范.

2021-06-19 12:16 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileList(self, group: Union[Group, int], dir: str = '') -> List[FileList]:
hmmm, maybe `path` is better than `dir`

2021-06-19 12:17 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileList(self, group: Union[Group, int], dir: str = '') -> List[FileList]:
我想知道为什么会出现两次这个方法

2021-06-19 12:17 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileInfo(self, group: Union[Group, int], id: str) -> FileConfig:
use `getGroupFileInfo`

2021-06-19 12:18 UTC, GreyElaina commented on src/graia/application/group.py
> +class FileConfig(BaseModel):
maybe you can rename to `FileInfo` instand of `FileConfig`

2021-06-19 12:19 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileMove(self, group: Union[Group, int], id: str, movePath: str) -> NoReturn:
rename:
 - `id` to `file_id`;
 - `movePath` to `move_to`.

2021-06-19 12:22 UTC, GreyElaina commented on src/graia/application/__init__.py
> +    async def groupFileDelete(self, group: Union[Group, int], id: str) -> NoReturn:
rename:
 - `groupFileDelete` to `removeGroupFile`
 - `id` to `file_id`

2021-06-19 12:22 UTC, GreyElaina commented on src/graia/application/__init__.py
> +        """
[排版规范](https://learnku.com/docs/writing-docs/typography/3957)

2021-06-19 12:26 UTC, GreyElaina requested changes
请按照以上要求修改

2021-06-23 14:38 UTC, GreyElaina commented
喂 怎么还不改

2021-06-24 13:46 UTC, GreyElaina approved these changes

2021-06-24 13:46 UTC, merged