Fix: Kanata doesn't work when Quote in MessageChain
GraiaProject/Application pull request #137
Opened 2021-06-23 10:19 UTC by jinzhijie

目前的情况：0: Quote, 1 以后：正文，At 和一个空格都不存在了
经过多种情况的测试，我这样修改机器人在各种情况下都成功做出了正确的反应

2021-06-23 14:50 UTC, GreyElaina requested changes

2021-06-23 14:50 UTC, GreyElaina commented on src/graia/application/message/parser/kanata.py
>              # 自动忽略自 Quote 后第一个 At
这可以删了

2021-06-24 07:11 UTC, jinzhijie commented on src/graia/application/message/parser/kanata.py
>              # 自动忽略自 Quote 后第一个 At
这几行全删掉？？不行的吧？

2021-06-24 13:47 UTC, GreyElaina commented on src/graia/application/message/parser/kanata.py
>              # 自动忽略自 Quote 后第一个 At
安卓端github有问题 313删了就ok

2021-06-25 01:35 UTC, GreyElaina approved these changes

2021-06-25 01:36 UTC, merged

2021-06-25 01:36 UTC, GreyElaina commented
还是希望先black一下。

2021-06-25 01:39 UTC, jinzhijie commented
> 还是希望先black一下。

这话说得不对，从日志来看，我没改的文件貌似也没有通过 black 吧？