加入正确的序列化/反序列化
GraiaProject/Application pull request #49
Opened 2020-10-25 03:29 UTC by melonedo

2020-10-25 06:20 UTC, GreyElaina requested changes
没有必要使用单独的模块置放方法/函数

2020-10-25 06:22 UTC, GreyElaina commented on src/graia/application/message/serializeChain.py
> +        i += 1
不够 pythonic:

``` python
for _ in range(length):
    ...
    continue # 使用这个替代 L44 的 i += 1
    ...
```

2020-10-25 06:24 UTC, GreyElaina commented on src/graia/application/message/serializeChain.py
> +}
搬到 `graia.application.message.chain` 模块下面吧.

2020-10-25 06:25 UTC, GreyElaina commented on src/graia/application/message/serializeChain.py
> +from graia.application.entry import MessageChain, Source, Plain, AtAll, At, Face, Image, FlashImage
请不要在内部使用 `graia.application.entry`, 这可能会导致潜在的 `circular import`

2020-10-25 06:26 UTC, GreyElaina commented on src/graia/application/message/chain.py
> +from .serializeChain import serializeChain, deserializeChain
方法使用 `camelCase`, 但独立的函数我还是建议使用 `snake_case`

2020-10-25 06:26 UTC, GreyElaina commented
请根据以上修改意见进行改进

2020-10-25 08:42 UTC, melonedo commented on src/graia/application/message/chain.py
> +from .serializeChain import serializeChain, deserializeChain
东西放进MessageChain里，无需命名

2020-10-29 14:48 UTC, GreyElaina commented on src/graia/application/message/chain.py
> +import re
请使用兼容但性能更好的 `regex` 库, 在上方已经 import 了

2020-10-29 14:52 UTC, GreyElaina commented on src/graia/application/message/serializeChain.py
> +}
在现有的代码中似乎会重复定义这个字典...虽然没什么, 不过你可以掂量下.

2020-10-29 14:54 UTC, GreyElaina commented
...还有就是, 请在 commit 时使用正规的语言, 最好是使用英文, 句意尽可能简短, 类似我尽力用的 angular 规范.

2020-11-02 08:17 UTC, melonedo commented on src/graia/application/message/serializeChain.py
> +}
原本这些元素也是在fromSerializationString里面定义的，防止循环引用。

2020-11-03 14:31 UTC, GreyElaina approved these changes

2020-11-03 14:33 UTC, merged

2020-11-03 14:35 UTC, GreyElaina commented
Congratulations.